source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘14.5’
use_frameworks!

def shared_pods
    pod 'Firebase/Auth', '~> 6.34.0'
    pod 'GoogleSignIn', '~> 6.2.1'
    pod 'wepin'
end


target 'WepinExample' do 
    shared_pods
end
